const EnumSpecializations = {
    ALLERGY_AND_IMMUNOLOGY: 'ALLERGY_AND_IMMUNOLOGY',
    ANESTHESIOLOGY: 'ANESTHESIOLOGY',
    CARDIOLOGY: 'CARDIOLOGY',
    CRITICAL_CARE_MEDICINE: 'CRITICAL_CARE_MEDICINE',
    DERMATOLOGY: 'DERMATOLOGY',
    EMERGENCY_MEDICINE: 'EMERGENCY_MEDICINE',
    ENDOCRINOLOGY: 'ENDOCRINOLOGY',
    FAMILY_MEDICINE: 'FAMILY_MEDICINE',
    GASTROENTEROLOGY: 'GASTROENTEROLOGY',
    GERIATRIC_MEDICINE: 'GERIATRIC_MEDICINE',
    HEMATOLOGY: 'HEMATOLOGY',
    INFECTIOUS_DISEASE: 'INFECTIOUS_DISEASE',
    INTERNAL_MEDICINE: 'INTERNAL_MEDICINE',
    MEDICAL_GENETICS: 'MEDICAL_GENETICS',
    NEONATOLOGY: 'NEONATOLOGY',
    NEPHROLOGY: 'NEPHROLOGY',
    NEUROLOGY: 'NEUROLOGY',
    OBSTETRICS_AND_GYNECOLOGY: 'OBSTETRICS_AND_GYNECOLOGY',
    ONCOLOGY: 'ONCOLOGY',
    OPHTHALMOLOGY: 'OPHTHALMOLOGY',
    ORTHOPEDICS: 'ORTHOPEDICS',
    OTOLARYNGOLOGY: 'OTOLARYNGOLOGY',
    PATHOLOGY: 'PATHOLOGY'
};

export default EnumSpecializations;
